In [2]:
import numpy as np

In [3]:
a = np.array([1,3,5], dtype="int16")

In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#Get dimension
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#Get shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
#get type
a.dtype

dtype('int16')

In [11]:
#get size
a.itemsize

2

In [12]:
b.itemsize

8

In [13]:
#Get total size
a.size

3

In [14]:
b.size

6

In [16]:
a.nbytes

6

In [17]:
a.size*a.itemsize

6

In [18]:
b.dtype

dtype('float64')

In [19]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# get a specific element [r, c]
a[1, 5]

np.int64(13)

In [21]:
a[1, -2]

np.int64(13)

In [22]:
#Get a specific row
a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
#Get a specific column
a[: , 2]

array([ 3, 10])

In [24]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [25]:
#to change element
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [26]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [27]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d Exmaple

In [28]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [29]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
#Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [31]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [32]:
# replace
b[:,1,:] = [[9,9],[8,8]]

In [33]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing DIfferent Types of Arrays

**Initializing Different Types of Arrays**

In [35]:
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [38]:
#All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [39]:
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [40]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [41]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.13875996, 0.93116249],
       [0.95700788, 0.16498739],
       [0.24227196, 0.23631242],
       [0.78567936, 0.13490102]])

In [44]:
np.random.rand(4,2,3)

array([[[0.14802133, 0.85575229, 0.13777933],
        [0.67744016, 0.76663195, 0.99593433]],

       [[0.64909192, 0.86598226, 0.75935553],
        [0.86914118, 0.76199666, 0.39738414]],

       [[0.08643653, 0.17368047, 0.11549335],
        [0.82874024, 0.11166366, 0.1269011 ]],

       [[0.9946404 , 0.81410434, 0.69236546],
        [0.26279221, 0.47449137, 0.46516817]]])

In [45]:
np.random.random_sample(a.shape)

array([[0.1168231 , 0.64067171, 0.13126258, 0.74922337, 0.5644958 ,
        0.62971391, 0.57936109],
       [0.11536676, 0.46728707, 0.157514  , 0.19845598, 0.48352015,
        0.643839  , 0.0183893 ]])

In [46]:
# Random Integer Values
np.random.randint(7, size=(3,3))

array([[2, 6, 6],
       [5, 1, 3],
       [2, 0, 6]])

In [51]:
np.random.randint(4,8, size=(3,3))

array([[4, 4, 6],
       [5, 6, 7],
       [7, 7, 4]])

In [53]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# Repeat Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [60]:
output[1:4, 1:4] = z

In [61]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be careful when copying arrays**

In [62]:
a = np.array([1,2,23])
b = a #variable b points to the same thing as a does 
b[0] = 100
print(a)

[100   2  23]


In [63]:
# to prevent this we use .copy() function
c = a.copy()
c[0] = 200
print(a)
print(c)

[100   2  23]
[200   2  23]


**Mathematics**

In [64]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [65]:
a + 2

array([3, 4, 5, 6])

In [66]:
a - 2

array([-1,  0,  1,  2])

In [67]:
a * 2

array([2, 4, 6, 8])

In [68]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [69]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [70]:
a ** 2

array([ 1,  4,  9, 16])

In [71]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear algebra

In [72]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [73]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [74]:
# Find the Determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

#### Statistics

In [76]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.min(stats)

np.int64(1)

In [79]:
np.max(stats, axis=1)

array([3, 6])

In [80]:
np.sum(stats)

np.int64(21)

In [81]:
np.sum(stats, axis = 0)

array([5, 7, 9])

#### Reorganizing arrays

In [84]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [86]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Micellaneous

**Load Data from File**

In [91]:
filedata = np.genfromtxt("data.txt", delimiter=",")
filedata.astype("int32")
filedata = filedata.astype("int32")
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Boolean masking and advanced indexing

In [92]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [93]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [94]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [95]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [96]:
np.all(filedata >50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [97]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])