In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [ ]:
X_train.shape

(60000, 28, 28)

In [ ]:
y_train.shape

(60000,)

In [ ]:
X_train, X_test = X_train/255.0, X_test/255.0

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input, Dropout

model = Sequential()
model.add(Input((28, 28)))
model.add(Flatten())
model.add(Dense(128, activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(10))

In [ ]:
nonsense_prediction = model(X_train[:1]).numpy()
nonsense_prediction

array([[ 0.14966403, -0.03425068,  0.24254458, -0.3049881 ,  0.03959238,
         0.13973652, -0.08954236,  0.8082673 ,  0.30653533, -0.68277323]],
      dtype=float32)

In [ ]:
tf.nn.softmax(nonsense_prediction).numpy()

array([[0.10231147, 0.08512384, 0.11226951, 0.0649339 , 0.09164754,
        0.1013008 , 0.08054495, 0.19767517, 0.11968856, 0.04450424]],
      dtype=float32)

In [ ]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

loss_fn = SparseCategoricalCrossentropy(from_logits = True)

loss_fn(y_train[:1], nonsense_prediction)

<tf.Tensor: shape=(), dtype=float32, numpy=2.289660930633545>

In [ ]:
from tensorflow.keras.optimizers import Adam

optimizer = Adam(learning_rate= 0.01)

model.compile(optimizer=optimizer, loss = loss_fn, metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9128 - loss: 0.3105
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9409 - loss: 0.2269
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9472 - loss: 0.2065
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9512 - loss: 0.1983
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9535 - loss: 0.1875
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9556 - loss: 0.1861
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9579 - loss: 0.1772
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9589 - loss: 0.1719
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9585 - loss: 0.1744
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9625 - loss: 0.1574


In [ ]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9505 - loss: 0.2669


[0.2669321894645691, 0.9505000114440918]

In [ ]:
import pandas as pd

df = pd.read_csv("housing.csv")

In [ ]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X, y = df.drop('MedHouseVal', axis = 1), df['MedHouseVal']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.20)

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_scaled

array([[-0.11065946, -0.85064944,  0.41217502, ..., -0.00239302,
         1.44216615, -0.90153699],
       [ 0.53877797,  0.33962254,  0.32813285, ..., -0.03277448,
        -0.86912982,  0.80372119],
       [ 1.68130287, -1.40610971,  0.78046793, ...,  0.02138131,
        -0.77987245,  0.86873103],
       ...,
       [ 0.40969527,  0.10156815, -0.02117902, ..., -0.02283735,
         0.78448031, -1.20658318],
       [ 0.30380297,  0.57767694,  0.08233414, ..., -0.02545724,
        -0.85973431,  0.71870832],
       [ 0.51759951, -0.05713479,  0.19702537, ..., -0.02320403,
        -0.55907792, -0.10641661]])

In [ ]:
X_train_scaled.shape

(16512, 8)

In [ ]:
model = Sequential()
model.add(Input((8,)))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(1))

In [ ]:
model.compile(optimizer='adam', loss='mse', metrics=['mae', 'r2_score'])

In [ ]:
model.fit(X_train_scaled, y_train, epochs = 10)

Epoch 1/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 0.7861 - mae: 0.6003 - r2_score: 0.4079 
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3973 - mae: 0.4495 - r2_score: 0.7008
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3664 - mae: 0.4295 - r2_score: 0.7240
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3574 - mae: 0.4220 - r2_score: 0.7309
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3482 - mae: 0.4088 - r2_score: 0.7377
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3350 - mae: 0.4016 - r2_score: 0.7477
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3196 - mae: 0.3939 - r2_score: 0.7593
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3110 - mae: 0.3868 - r2_score: 0.7658
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3229 - mae: 0.3859 - r2_score: 0.7568
Epoch 10/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3105 - mae: 0.3816 - r2_score: 0.766

In [ ]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2975 - mae: 0.3872 - r2_score: 0.7790


[0.29754874110221863, 0.38722673058509827, 0.7789740562438965]

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [ ]:
scalar = tf.constant(7)

In [ ]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

TensorShape([2, 2])

In [ ]:
matrix.dtype

tf.int32

In [ ]:
matrix.ndim

2

In [ ]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros_like(matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [ ]:
tf.random.normal([3,3], mean= 0, stddev = 1)
tf.random.uniform([3,3], minval=0, maxval=1)
tf.random.set_seed(42)

In [ ]:
tf.range(0, 10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [ ]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
import numpy as np
arr = np.array([1.0, 2.0, 3.0])
t = tf.constant(arr)

In [ ]:
a = tf.constant([[1,2], [3,4]], dtype = tf.float32)
b = tf.constant([[5,6], [7,8]], dtype=tf.float32)

In [ ]:
tf.add(a,b)
tf.subtract(a,b)
tf.multiply(a,b)
tf.divide(a,b)

tf.matmul(a,b)

tf.reduce_sum(a)
tf.reduce_mean(a)
tf.reduce_max(a, axis=0)
tf.reduce_min(a, axis=1)

x = tf.constant([1,2,3,4,5,6])
x_reshaped = tf.reshape(x, [2,3])
x_flat = tf.reshape(x_reshaped, [-1])

tf.transpose(a)

tf.cast(a, dtype=tf.int32)

tf.abs(tf.constant([-1.0, 2.0]))
tf.square(a)
tf.sqrt(tf.constant([4.0, 9.0]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [ ]:
t = tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])

t[0]
t[:, 1]
t[1:, 1:]
t[0,2]

mask = tf.constant([True, False, True])
tf.boolean_mask(t, mask, axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]], dtype=int32)>

In [ ]:
w = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
b = tf.Variable(0.0)

print(w.numpy())

w.assign([[5.0, 6.0],[7.0, 8.0]])

w.assign_add([[1.0, 0.0], [0.0, 1.0]])


[[1. 2.]
 [3. 4.]]


<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[6., 6.],
       [7., 9.]], dtype=float32)>

In [ ]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
  y = x**2 + 2 * x + 1

dy_dx = tape.gradient(y, x)
print(dy_dx.numpy())

x = tf.Variable(2.0)
z = tf.Variable(3.0)

with tf.GradientTape() as tape:
  f = x**2 * 2 + z**3

grads = tape.gradient(f, [x, z])
print(grads[0].numpy())
print(grads[1].numpy())

with tf.GradientTape(persistent=True) as tape:
  y = x ** 3

g1 = tape.gradient(y, x)
g2 = tape.gradient(y, x)
del tape

8.0
8.0
27.0


In [ ]:
import tensorflow as tf
import numpy as np

np.random.seed(42)
X = np.linspace(0, 1, 100).astype(np.float32)
y = 2 * X + 1 + np.random.normal(0, 0.1, 100).astype(np.float32)

w = tf.Variable(0.0)
b = tf.Variable(0.0)

def predict(x):
  return w * x + b

def mse_loss(y_pred, y_true):
  return tf.reduce_mean((y_pred-y_true)**2)

learning_rate = 0.1
for epoch in range(200):
  with tf.GradientTape() as tape:
    y_pred = predict(X)
    loss = mse_loss(y_pred, y)

  grads = tape.gradient(loss, [w, b])
  w.assign_sub(learning_rate * grads[0])
  b.assign_sub(learning_rate * grads[1])

  if epoch % 40 == 0:
    print(f"Epoch {epoch}: loss={loss.numpy():.4f}, w={w.numpy():.3f}, b={b.numpy():.3f}")



print(f"\nLearned: w={w.numpy():.3f}, b={b.numpy():.3f}")


Epoch 0: loss=4.3115, w=0.233, b=0.398
Epoch 40: loss=0.0473, w=1.350, b=1.339
Epoch 80: loss=0.0214, w=1.627, b=1.190
Epoch 120: loss=0.0127, w=1.788, b=1.104
Epoch 160: loss=0.0097, w=1.882, b=1.053

Learned: w=1.936, b=1.024


In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
a = tf.constant(5)

In [ ]:
print(a)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
b = tf.constant([1,2,3])

In [ ]:
print(b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
c = tf.constant([[1,2], [3,4]])

In [ ]:
print(c)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
d = tf.constant([[[1,2], [3,4]], [[5,6], [7,8]]])

In [ ]:
print(d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
e = tf.constant(3.14, dtype = tf.float32)

In [ ]:
print(e)

tf.Tensor(3.14, shape=(), dtype=float32)


In [ ]:
f = tf.constant(True, dtype=tf.bool)

In [ ]:
f = tf.constant(True, dtype=tf.bool)

In [ ]:
print(f)

tf.Tensor(True, shape=(), dtype=bool)


In [ ]:
print(f.shape)

()


In [ ]:
print(f.dtype)

<dtype: 'bool'>


In [ ]:
print(f.ndim)

0


In [ ]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros_like(c)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [ ]:
tf.random.normal([3,3], mean = 0, stddev=1.0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

In [ ]:
tf.random.uniform([3,3], minval=0, maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.803156  , 0.49777734, 0.37054038],
       [0.9118674 , 0.637642  , 0.18209696],
       [0.63791955, 0.27701473, 0.04227114]], dtype=float32)>

In [ ]:
tf.random.set_seed(42)

In [ ]:
tf.range(0, 10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [ ]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
import numpy as np
arr = np.array([1.0, 2.0, 3.0])
tf.constant(arr)

NameError: name 'tf' is not defined

In [ ]:
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype = tf.float32)

In [ ]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float32)>

In [ ]:
tf.subtract(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4., -4.],
       [-4., -4.]], dtype=float32)>

In [ ]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5., 12.],
       [21., 32.]], dtype=float32)>

In [ ]:
tf.divide(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.2       , 0.33333334],
       [0.42857143, 0.5       ]], dtype=float32)>

In [ ]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [ ]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [ ]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [ ]:
tf.reduce_max(a, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

In [ ]:
tf.reduce_min(a, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 3.], dtype=float32)>

In [ ]:
x = tf.constant([1,2,3,4,5,6])
x_reshaped = tf.reshape(x, [2,3])

In [ ]:
x_flat = tf.reshape(x_reshaped, [-1])

In [ ]:
tf.transpose(x_reshaped)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
tf.cast(x_reshaped, dtype= tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.abs(tf.constant([-1.0, 2.0]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [ ]:
tf.square(x_reshaped)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [ ]:
tf.sqrt(tf.constant([4.0, 9.0]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [ ]:
t = tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
t[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
t[:, 1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 8], dtype=int32)>

In [ ]:
t[1:, 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [8, 9]], dtype=int32)>

In [ ]:
t[0,2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
mask = tf.constant([True, False, True])
tf.boolean_mask(t, mask, axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]], dtype=int32)>

In [ ]:
w = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

In [ ]:
b = tf.Variable(0.0)

In [ ]:
print(w)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


In [ ]:
w.assign([[5.0, 6.0], [7.0, 8.0]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float32)>

In [ ]:
w.assign_add([[1.0, 0.0], [0.0, 1.0]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[6., 6.],
       [7., 9.]], dtype=float32)>

In [ ]:
w.assign_sub([[1.0, 0.0], [0.0, 1.0]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float32)>

In [ ]:
x = tf.Variable(3.0)

In [ ]:
with tf.GradientTape() as tape:
  y = x**2 + 2*x + 1

In [ ]:
dy_dx = tape.gradient(y, x)

In [ ]:
print(dy_dx.numpy())

8.0


In [ ]:
x = tf.Variable(2.0)
z = tf.Variable(3.0)

In [ ]:
with tf.GradientTape() as tape:
  f = x**2 * z + z**3

In [ ]:
grads = tape.gradient(f, [x, z])

In [ ]:
print(grads[0].numpy())
print(grads[1].numpy())

12.0
31.0


In [ ]:
g1 = tape.gradient(y, x)
g2 = tape.gradient(y, x)

In [ ]:
del tape

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
np.random.seed(42)

In [ ]:
X = np.linspace(0, 1, 100).astype(np.float32)

In [ ]:
y = 2*X + 1 + np.random.normal(0, 0.1, 100).astype(np.float32)

In [ ]:
w = tf.Variable(0.0)
b = tf.Variable(0.0)

In [ ]:
def predict(x):
  return w * x + b

In [ ]:
def mse_loss(y_pred, y_true):
  return tf.reduce_mean((y_pred - y_true) ** 2)

In [ ]:
learning_rate = 0.1

In [ ]:
for epoch in range(200):
  with tf.GradientTape() as tape:
    y_pred = predict(X)
    loss = mse_loss(y_pred, y)
  grads = tape.gradient(loss, [w, b])
  w.assign_sub(learning_rate * grads[0])
  b.assign_sub(learning_rate * grads[1])

  if epoch % 40 == 0:
    print(f"Epoch {epoch}: loss={loss.numpy() :.4f}, w={w.numpy():.3f}, b={b.numpy():.3f}")

Epoch 0: loss=4.3115, w=0.233, b=0.398
Epoch 40: loss=0.0473, w=1.350, b=1.339
Epoch 80: loss=0.0214, w=1.627, b=1.190
Epoch 120: loss=0.0127, w=1.788, b=1.104
Epoch 160: loss=0.0097, w=1.882, b=1.053


In [ ]:
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(20,)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 64)             │         1,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,457 (13.50 KB)

 Trainable params: 3,457 (13.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    optimizer = 'adam',
    loss = 'mse',
    metrics = ['mae'],

)

In [ ]:
X_train = np.random.randn(1000, 20).astype(np.float32)
y_train = np.random.randn(1000, 1).astype(np.float32)

In [ ]:
history = model.fit(X_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_split=0.2,
                    verbose=1)

Epoch 1/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 5s 72ms/step - loss: 1.0939 - mae: 0.8328 - val_loss: 1.1284 - val_mae: 0.8189
Epoch 2/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0242 - mae: 0.8034 - val_loss: 1.0591 - val_mae: 0.7903
Epoch 3/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.9724 - mae: 0.7844 - val_loss: 1.0664 - val_mae: 0.7885
Epoch 4/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.9360 - mae: 0.7679 - val_loss: 1.0622 - val_mae: 0.7870
Epoch 5/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.9053 - mae: 0.7552 - val_loss: 1.0478 - val_mae: 0.7802
Epoch 6/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.8740 - mae: 0.7420 - val_loss: 1.0511 - val_mae: 0.7825
Epoch 7/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.8465 - mae: 0.7303 - val_loss: 1.0445 - val_mae: 0.7809
Epoch 8/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.8208 - mae: 0.7187 - val_loss: 1.0593 - val_mae: 0.7863
Epoch 9/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.793

In [ ]:
X_test = np.random.randn(200, 20).astype(np.float32)
y_test = np.random.randn(200, 1).astype(np.float32)

In [ ]:
test_loss, test_mae = model.evaluate(X_test, y_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1173 - mae: 0.8518 


In [ ]:
print(f"Test loss: {test_loss:.4f}, Test MAE: {test_mae:.4f}")

Test loss: 1.1173, Test MAE: 0.8518


In [ ]:
predictions = model.predict(X_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


In [ ]:
print(predictions)

[[-0.06101189]
 [ 0.23192742]
 [ 0.09056672]
 [-0.06543738]
 [ 0.28353277]
 [-0.03798938]
 [-0.1353995 ]
 [-0.12302807]
 [-0.4875875 ]
 [ 0.1511972 ]
 [-0.22212005]
 [ 0.7066063 ]
 [-0.02663914]
 [-0.07810857]
 [-0.6741949 ]
 [ 0.05393944]
 [-0.05021274]
 [-0.28530553]
 [-0.5417781 ]
 [-0.14956412]
 [-0.35748076]
 [-0.3582105 ]
 [-0.2960768 ]
 [ 0.09028725]
 [ 0.42803904]
 [-0.13066158]
 [ 0.38559777]
 [-0.11803003]
 [-0.41637525]
 [-0.58283997]
 [-0.1293354 ]
 [-0.28668216]
 [-0.18142524]
 [-0.09678655]
 [-0.16499159]
 [ 0.5045937 ]
 [ 0.3558737 ]
 [ 0.25719336]
 [ 0.09833093]
 [ 0.0195986 ]
 [-0.20313525]
 [-0.52630854]
 [-0.03593876]
 [ 0.3845801 ]
 [-0.29628232]
 [ 0.04086477]
 [ 0.08950033]
 [-0.31226495]
 [ 0.1585334 ]
 [-0.36446616]
 [ 0.36776748]
 [-0.14454004]
 [-0.26337004]
 [ 0.29700765]
 [ 0.12962931]
 [ 0.12496341]
 [ 0.5028686 ]
 [ 0.2597475 ]
 [ 0.10523281]
 [ 0.27550295]
 [ 0.35592663]
 [ 0.10555566]
 [-0.06764345]
 [-0.12903494]
 [-0.48098505]
 [-0.4213129 ]
 [ 0.22610

In [ ]:
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense, concatenate

In [ ]:
input_a = Input(shape=(10,), name="input_a")
input_b = Input(shape=(5,), name="input_b")

x = Dense(32, activation='relu')(input_a)
y = Dense(16, activation='relu')(input_b)

merged = concatenate([x, y])

In [ ]:
output = Dense(1, activation='sigmoid', name='output')(merged)

In [ ]:
model = Model(inputs=[input_a, input_b], outputs=output)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
X_a = np.random.randn(500, 10).astype(np.float32)
X_b = np.random.randn(500, 5).astype(np.float32)
labels = np.random.randint(0, 2, 500).astype(np.float32)

In [ ]:
model.fit({"input_a": X_a, "input_b": X_b}, labels, epochs=5)

Epoch 1/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5220 - loss: 0.7232
Epoch 2/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5360 - loss: 0.7116 
Epoch 3/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5360 - loss: 0.7052 
Epoch 4/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5280 - loss: 0.7002 
Epoch 5/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5360 - loss: 0.6957 


In [ ]:
layers.Dense(128, activation='relu')

<Dense name=dense_2, built=False>

In [ ]:
layers.Dropout(0.5)

<Dropout name=dropout, built=True>

In [ ]:
layers.BatchNormalization()

<BatchNormalization name=batch_normalization, built=False>

In [ ]:
layers.Activation('relu')

<Activation name=activation, built=True>

In [ ]:
layers.ReLU()

<ReLU name=re_lu, built=True>

In [ ]:
layers.LeakyReLU(alpha = 0.2)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/activations/leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(


<LeakyReLU name=leaky_re_lu, built=True>

In [ ]:
layers.Softmax()

<Softmax name=softmax, built=True>

In [ ]:
layers.Flatten()

<Flatten name=flatten, built=False>

In [ ]:
layers.Reshape((7,7,64))

<Reshape name=reshape, built=True>

In [ ]:
layers.Embedding(input_dim=10000, output_dim=64)

In [ ]:
model = keras.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    layers.Conv2D(32, (3,3), activation='relu', padding='same'),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.25),
    layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.25),
    layers.Flatten(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
from tensorflow.keras import models
model = models.Sequential([
    layers.LSTM(64, return_sequences=True, input_shape=(50, 10)),
    layers.LSTM(32),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
layers.GRU(64, return_sequences=True, input_shape=(50, 10))

<GRU name=gru, built=False>

In [ ]:
layers.Bidirectional(layers.LSTM(64))

<Bidirectional name=bidirectional, built=False>

In [ ]:
class MyMLP(tf.keras.Model):
  def __init__(self):
    self.dense1 = tf.keras.layers.Dense(64, activation='relu')
    self.dense2 = tf.keras.layers.Dense(32, activation='relu')
    self.out = tf.keras.layers.Dense(10, activation='softmax')
    self.dropout = tf.keras.layers.Dropout(0.3)

  def call(self, inputs, training=False):
    x = self.dense1(inputs)
    x = self.dropout(x, training=training)
    x = self.dense2(x)
    return self.out(x)

model = MyMLP()
dummy = tf.random.normal([4, 20])
out = model(dummy, training=True)
print(out.shape)

RuntimeError: In layer 'MyMLP', you forgot to call `super().__init__()` as the first statement in the `__init__()` method. Go add it!

In [ ]:
tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9)

In [ ]:
tf.keras.optimizers.Adam(learning_rate = 0.001, beta_1 = 0.9, beta_2= 0.999)

In [ ]:
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=0.01,
    decay_steps=1000,
    decay_rate=0.96,
    staircase=True
)

optimizer = tf.keras.optimizers.Adam(learning_rate = lr_schedule)

In [ ]:
tf.keras.losses.MeanSquaredError()

<LossFunctionWrapper(<function mean_squared_error at 0x7bab377b1c60>, kwargs={})>

In [ ]:
tf.keras.losses.MeanAbsoluteError()

<LossFunctionWrapper(<function mean_absolute_error at 0x7bab377b1d00>, kwargs={})>

In [ ]:
tf.keras.losses.Huber(delta=1.0)

<LossFunctionWrapper(<function huber at 0x7bab377b1f80>, kwargs={'delta': 1.0})>

In [ ]:
tf.keras.losses.BinaryCrossentropy()

<LossFunctionWrapper(<function binary_crossentropy at 0x7bab377b23e0>, kwargs={'from_logits': False, 'label_smoothing': 0.0, 'axis': -1})>

In [ ]:
from tensorflow.keras import models, losses

In [ ]:
tf.keras.losses.CategoricalCrossentropy()

<LossFunctionWrapper(<function categorical_crossentropy at 0x7a5c18807d80>, kwargs={'from_logits': False, 'label_smoothing': 0.0, 'axis': -1})>

In [ ]:
import tensorflow as tf

In [ ]:
tf.keras.losses.SparseCategoricalCrossentropy()

<LossFunctionWrapper(<function sparse_categorical_crossentropy at 0x7a5c18807ec0>, kwargs={'from_logits': False, 'ignore_class': None, 'axis': -1})>

In [ ]:
from tensorflow.keras import regularizers
layers.Dense(64, activation='relu', kernel_regularizer = regularizers.L2(0.01),
  bias_regularizer = regularizers.L1(0.001))

<Dense name=dense, built=False>

In [ ]:
from tensorflow.keras import layers

In [ ]:
regularizers.L1L2(l1=0.01, l2=0.01)

In [ ]:
layers.Dropout(rate=0.5)

<Dropout name=dropout, built=True>

In [ ]:
layers.BatchNormalization()

<BatchNormalization name=batch_normalization, built=False>

In [4]:
import tensorflow as tf

In [5]:
print(tf.__version__)

2.20.0


In [6]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [7]:
a = tf.constant(5)

In [8]:
print(a)

tf.Tensor(5, shape=(), dtype=int32)


In [9]:
b = tf.constant([1,2,3])

In [10]:
print(b.shape)

(3,)


In [11]:
c = tf.constant([[1, 2], [3, 4]])

In [12]:
print(c.shape)

(2, 2)


In [13]:
d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [14]:
print(d.shape)

(2, 2, 2)


In [15]:
e = tf.constant(3.14, dtype=tf.float32)

In [16]:
f = tf.constant(True, dtype=tf.bool)

In [17]:
print(f.shape)

()


In [18]:
print(f.dtype)

<dtype: 'bool'>


In [19]:
print(c.dtype)

<dtype: 'int32'>


In [20]:
print(c.ndim)

2


In [21]:
print(a.ndim)

0


In [22]:
print(b.ndim)

1


In [23]:
print(c.ndim)

2


In [24]:
print(d.ndim)

3


In [25]:
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [26]:
tf.ones([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [27]:
tf.zeros_like(c)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [28]:
tf.random.normal([3, 3], mean=0, stddev=1.0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.40023044,  0.32917064, -0.4748475 ],
       [ 0.5009574 , -0.8103392 ,  1.1891123 ],
       [ 0.39465982,  0.38960496, -0.6189926 ]], dtype=float32)>

In [29]:
tf.random.uniform([3,3], minval = 0, maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.59733796, 0.86609507, 0.8253552 ],
       [0.4704473 , 0.87855947, 0.08239663],
       [0.45171368, 0.03868127, 0.67186236]], dtype=float32)>

In [30]:
tf.random.set_seed(42)

In [31]:
tf.range(0, 10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [32]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [33]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [34]:
import numpy as np
arr = np.array([1.0, 2.0, 3.0])
t = tf.constant(arr)

In [35]:
a = tf.constant([[1, 2], [3, 7]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

In [36]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [10., 15.]], dtype=float32)>

In [37]:
tf.subtract(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4., -4.],
       [-4., -1.]], dtype=float32)>

In [38]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5., 12.],
       [21., 56.]], dtype=float32)>

In [39]:
tf.divide(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.2       , 0.33333334],
       [0.42857143, 0.875     ]], dtype=float32)>

In [40]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [64., 74.]], dtype=float32)>

In [41]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float32, numpy=13.0>

In [43]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=3.25>

In [44]:
tf.reduce_max(a, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 7.], dtype=float32)>

In [45]:
tf.reduce_min(a, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 3.], dtype=float32)>

In [46]:
x = tf.constant([1,2,3,4,5,6])
x_reshaped = tf.reshape(x, [2, 3])

In [47]:
print(x_reshaped)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [48]:
x_flat = tf.reshape(x_reshaped, [-1])

In [49]:
print(x_flat)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [50]:
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [2., 7.]], dtype=float32)>

In [51]:
tf.cast(a, dtype = tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 7]], dtype=int32)>

In [52]:
tf.abs(tf.constant([-1.0, 2.0]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [53]:
tf.square(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  4.],
       [ 9., 49.]], dtype=float32)>

In [54]:
tf.sqrt(tf.constant([4.0, 9.0]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [55]:
t = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [56]:
t[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [57]:
t[:, 1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 8], dtype=int32)>

In [58]:
t[1:, 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [8, 9]], dtype=int32)>

In [59]:
t[0, 2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [60]:
mask = tf.constant([True, False, True])
tf.boolean_mask(t, mask, axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]], dtype=int32)>

In [62]:
w = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

In [63]:
b = tf.Variable(0.0)

In [64]:
print(w.numpy())

[[1. 2.]
 [3. 4.]]


In [65]:
print(w)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


In [66]:
w.assign([[5.0, 6.0], [7.0, 8.0]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float32)>

In [67]:
w.assign_add([[1.0, 0.0], [0.0, 1.0]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[6., 6.],
       [7., 9.]], dtype=float32)>

In [68]:
x = tf.Variable(3.0)

In [69]:
with tf.GradientTape() as tape:
  y = x ** 2 + 2*x + 1

In [70]:
dy_dx = tape.gradient(y, x)

In [71]:
print(dy_dx.numpy())

8.0


In [73]:
x = tf.Variable(2.0)
z = tf.Variable(3.0)

In [74]:
with tf.GradientTape() as tape:
  f = x**2 * z + z**3

In [75]:
grads = tape.gradient(f, [x, z])

In [76]:
print(grads[0].numpy())
print(grads[1].numpy())

12.0
31.0


In [77]:
with tf.GradientTape(persistent = True) as tape:
  y = x ** 3

In [78]:
g1 = tape.gradient(y, x)
g2 = tape.gradient(y, x)

In [79]:
del tape

In [80]:
import tensorflow as tf
import numpy as np

In [81]:
np.random.seed(42)

In [82]:
X = np.linspace(0, 1, 100).astype(np.float32)

In [83]:
y = 2*X + 1 + np.random.normal(0, 0.1, 100).astype(np.float32)

In [84]:
w = tf.Variable(0.0)
b = tf.Variable(0.0)

In [85]:
def predict(x):
  return w * x + b

In [86]:
def mse_loss(y_pred, y_true):
  return tf.reduce_mean((y_pred - y_true) ** 2)

In [87]:
learning_rate = 0.1

In [88]:
for epoch in range(200):
  with tf.GradientTape() as tape:
    y_pred = predict(X)
    loss = mse_loss(y_pred, y)
  grads = tape.gradient(loss, [w, b])
  w.assign_sub(learning_rate * grads[0])
  b.assign_sub(learning_rate * grads[1])

  if epoch % 40 == 0:
    print(f"Epoch {epoch}: loss{loss.numpy():.4f}, w={w.numpy():.3f}, b={b.numpy():.3f}")

Epoch 0: loss4.3115, w=0.233, b=0.398
Epoch 40: loss0.0473, w=1.350, b=1.339
Epoch 80: loss0.0214, w=1.627, b=1.190
Epoch 120: loss0.0127, w=1.788, b=1.104
Epoch 160: loss0.0097, w=1.882, b=1.053


In [89]:
from tensorflow import keras
from tensorflow.keras import layers

In [90]:
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(20, )),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)
])

model .summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,457 (13.50 KB)

 Trainable params: 3,457 (13.50 KB)

 Non-trainable params: 0 (0.00 B)

In [92]:
model.compile(
    optimizer = 'adam',
    loss = 'mse',
    metrics = ['mae']
)

In [93]:
import numpy as np
X_train = np.random.randn(1000, 20).astype(np.float32)

In [94]:
y_train = np.random.randn(1000, 1).astype(np.float32)

In [95]:
history = model.fit(
    X_train, y_train,
    epochs = 10,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)



Epoch 1/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - loss: 1.0934 - mae: 0.8342 - val_loss: 1.1062 - val_mae: 0.8200
Epoch 2/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.9972 - mae: 0.7947 - val_loss: 1.1128 - val_mae: 0.8230
Epoch 3/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9548 - mae: 0.7758 - val_loss: 1.1156 - val_mae: 0.8242
Epoch 4/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9222 - mae: 0.7617 - val_loss: 1.1194 - val_mae: 0.8256
Epoch 5/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8931 - mae: 0.7493 - val_loss: 1.1214 - val_mae: 0.8262
Epoch 6/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.8660 - mae: 0.7378 - val_loss: 1.1238 - val_mae: 0.8277
Epoch 7/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.8396 - mae: 0.7267 - val_loss: 1.1268 - val_mae: 0.8288
Epoch 8/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8145 - mae: 0.7160 - val_loss: 1.1336 - val_mae: 0.8309
Epoch 9/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7900 - m

In [96]:
X_test = np.random.randn(200, 20).astype(np.float32)
y_test = np.random.randn(200, 1).astype(np.float32)

In [97]:
test_loss, test_mae = model.evaluate(X_test, y_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0444 - mae: 0.8284


In [98]:
print(f"Test loss: {test_loss:.4f}, Test MAE: {test_mae:.4f}")

Test loss: 1.0444, Test MAE: 0.8284


In [99]:
predictions = model.predict(X_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


In [101]:
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense, concatenate

In [102]:
input_a = Input(shape=(10,), name="input_a")

In [103]:
input_b = Input(shape=(5,), name="input_b")

In [104]:
x = Dense(32, activation='relu')(input_a)

In [105]:
y = Dense(16, activation='relu')(input_b)

In [106]:
merged = concatenate([x, y])

In [107]:
output = Dense(1, activation='sigmoid', name='output')(merged)

In [108]:
model = Model(inputs = [input_a, input_b], outputs=output)

In [109]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [110]:
X_a = np.random.randn(500, 10).astype(np.float32)
X_b = np.random.randn(500, 5).astype(np.float32)
labels = np.random.randint(0, 2, 500).astype(np.float32)

In [111]:
model.fit({"input_a": X_a, "input_b": X_b}, labels, epochs=5)

Epoch 1/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 6s 180ms/step - accuracy: 0.5140 - loss: 0.7209
Epoch 2/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5280 - loss: 0.7006
Epoch 3/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5400 - loss: 0.6901
Epoch 4/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5440 - loss: 0.6834
Epoch 5/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5460 - loss: 0.6783


In [112]:
layers.Dense(128, activation='relu')

<Dense name=dense_5, built=False>

In [113]:


layers.Dropout(0.5)

<Dropout name=dropout, built=True>

In [114]:
layers.BatchNormalization()

<BatchNormalization name=batch_normalization, built=False>

In [115]:
layers.Activation('relu')

<Activation name=activation, built=True>

In [117]:


layers.LeakyReLU(alpha=0.2)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/activations/leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(


<LeakyReLU name=leaky_re_lu, built=True>

In [118]:
layers.Softmax()

<Softmax name=softmax, built=True>

In [120]:
layers.Flatten()

<Flatten name=flatten, built=False>

In [121]:
layers.Reshape((7,7,64))

<Reshape name=reshape, built=True>

In [122]:
layers.Embedding(input_dim=10000, output_dim=64)

<Embedding name=embedding, built=False>

In [126]:
from tensorflow.keras import models

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    layers.Flatten(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation = 'softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [127]:
model.compile(optimizer='adam',
              loss = 'categorical_crossentropy',
              metrics=['accuracy'])

In [128]:
model = models.Sequential([
    layers.LSTM(64, return_sequences=True, input_shape=(50, 10)),
    layers.LSTM(32),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [129]:
layers.GRU(64, return_sequences=True, input_shape=(50, 10))

<GRU name=gru, built=False>

In [130]:
layers.Bidirectional(layers.LSTM(64))

<Bidirectional name=bidirectional, built=False>