In [296]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [297]:
df = pd.read_csv("Train.csv")

In [298]:
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1


In [299]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   10999 non-null  int64 
 1   Warehouse_block      10999 non-null  object
 2   Mode_of_Shipment     10999 non-null  object
 3   Customer_care_calls  10999 non-null  int64 
 4   Customer_rating      10999 non-null  int64 
 5   Cost_of_the_Product  10999 non-null  int64 
 6   Prior_purchases      10999 non-null  int64 
 7   Product_importance   10999 non-null  object
 8   Gender               10999 non-null  object
 9   Discount_offered     10999 non-null  int64 
 10  Weight_in_gms        10999 non-null  int64 
 11  Reached.on.Time_Y.N  10999 non-null  int64 
dtypes: int64(8), object(4)
memory usage: 1.0+ MB


In [300]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,10999.0,5500.000000,3175.282140,1.0,2750.5,5500.0,8249.5,10999.0
Customer_care_calls,10999.0,4.054459,1.141490,2.0,3.0,4.0,5.0,7.0
Customer_rating,10999.0,2.990545,1.413603,1.0,2.0,3.0,4.0,5.0
Cost_of_the_Product,10999.0,210.196836,48.063272,96.0,169.0,214.0,251.0,310.0
Prior_purchases,10999.0,3.567597,1.522860,2.0,3.0,3.0,4.0,10.0
Discount_offered,10999.0,13.373216,16.205527,1.0,4.0,7.0,10.0,65.0
Weight_in_gms,10999.0,3634.016729,1635.377251,1001.0,1839.5,4149.0,5050.0,7846.0
Reached.on.Time_Y.N,10999.0,0.596691,0.490584,0.0,0.0,1.0,1.0,1.0


In [301]:
import seaborn as sns

In [302]:
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1


In [303]:
from sklearn.model_selection import train_test_split

In [304]:
X = df.drop("Reached.on.Time_Y.N", axis= 1)

In [305]:
X.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms
0,1,D,Flight,4,2,177,3,low,F,44,1233
1,2,F,Flight,4,5,216,2,low,M,59,3088
2,3,A,Flight,2,2,183,4,low,M,48,3374
3,4,B,Flight,3,3,176,4,medium,M,10,1177
4,5,C,Flight,2,2,184,3,medium,F,46,2484


In [306]:
y = df["Reached.on.Time_Y.N"]

In [307]:
y.head()

,Reached.on.Time_Y.N
0,1
1,1
2,1
3,1
4,1


In [308]:
print(y.value_counts(normalize=True))

Reached.on.Time_Y.N
1    0.596691
0    0.403309
Name: proportion, dtype: float64


In [309]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42, shuffle=True)

In [310]:
X_train

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms
8965,8966,F,Ship,3,5,178,3,low,F,7,4135
5936,5937,A,Ship,6,3,202,4,medium,F,3,4496
10656,10657,D,Ship,2,5,277,3,medium,M,6,1032
3328,3329,C,Ship,5,5,219,2,medium,M,4,4289
9880,9881,C,Flight,6,3,296,4,low,F,4,1650
...,...,...,...,...,...,...,...,...,...,...,...
5734,5735,C,Road,3,5,275,2,low,F,7,4619
5191,5192,F,Road,5,5,187,4,medium,F,9,5326
5390,5391,A,Ship,4,2,137,2,medium,F,2,5804
860,861,A,Ship,5,3,144,6,medium,F,35,1009


In [311]:
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

In [312]:
X_train_processed = X_train.drop('ID', axis=1)

In [313]:
X_test_processed = X_test.drop('ID', axis=1)


In [314]:
X_train_processed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8799 entries, 8965 to 7270
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Warehouse_block      8799 non-null   object
 1   Mode_of_Shipment     8799 non-null   object
 2   Customer_care_calls  8799 non-null   int64 
 3   Customer_rating      8799 non-null   int64 
 4   Cost_of_the_Product  8799 non-null   int64 
 5   Prior_purchases      8799 non-null   int64 
 6   Product_importance   8799 non-null   object
 7   Gender               8799 non-null   object
 8   Discount_offered     8799 non-null   int64 
 9   Weight_in_gms        8799 non-null   int64 
dtypes: int64(6), object(4)
memory usage: 756.2+ KB


In [315]:
X_train_cat = X_train_processed.select_dtypes(include = ['category', 'object'])

In [316]:
X_train_num = X_train_processed.select_dtypes(include= ['int64'])

In [317]:
X_test_cat = X_test_processed.select_dtypes(include = ['category', 'object'])
X_test_num = X_test_processed.select_dtypes(include= ['int64'])

In [318]:
ohe = OneHotEncoder()
X_train_ohe = ohe.fit_transform(X_train_cat)
X_test_ohe = ohe.transform(X_test_cat)

In [319]:
print(X_train_ohe.toarray())

[[0. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 0. 1.]
 ...
 [1. 0. 0. ... 1. 1. 0.]
 [1. 0. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]]


In [320]:
scaler = MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train_num)
X_test_scale = scaler.transform(X_test_num)

In [321]:
X_test_scale

array([[0.4       , 1.        , 0.56074766, 0.125     , 0.390625  ,
        0.15368882],
       [0.2       , 0.        , 0.57943925, 0.125     , 0.078125  ,
        0.66778671],
       [0.2       , 0.25      , 0.55607477, 0.25      , 0.03125   ,
        0.44426589],
       ...,
       [0.2       , 0.75      , 0.48130841, 0.125     , 0.140625  ,
        0.57326516],
       [0.        , 0.25      , 0.30373832, 0.125     , 0.0625    ,
        0.73016801],
       [0.2       , 1.        , 0.55140187, 0.125     , 0.078125  ,
        0.63082542]])

In [322]:
X_train_ohe_dense = X_train_ohe.toarray()
X_test_ohe_dense = X_test_ohe.toarray()

In [323]:
X_train_final = np.concatenate((X_train_scale, X_train_ohe_dense), axis=1)
X_test_final = np.concatenate((X_test_scale, X_test_ohe_dense), axis=1)

In [324]:
X_train_final.shape[1]

19

In [325]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input, Dropout
from tensorflow.keras.optimizers import Adam

In [326]:
custom_learning_rate = 0.001

custom_adam = Adam(learning_rate=custom_learning_rate)

In [327]:
model = Sequential([
    tf.keras.Input(shape = (19,)),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation = 'relu'),
    Dropout(0.3),
    Dense(2, activation='softmax')
])

In [328]:
model.compile(optimizer = custom_adam,
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

In [329]:
y_train_ohe = tf.keras.utils.to_categorical(y_train, num_classes=2)
y_test_ohe = tf.keras.utils.to_categorical(y_test, num_classes=2)


model.build((None, X_train_final.shape[1]))

history = model.fit(
    X_train_final,
    y_train_ohe,
    epochs = 50,
    verbose= 2,
    batch_size= 32,
    validation_data = (X_test_final, y_test_ohe)
)

Epoch 1/50
275/275 - 3s - 13ms/step - accuracy: 0.6130 - loss: 0.6117 - val_accuracy: 0.6582 - val_loss: 0.5458
Epoch 2/50
275/275 - 1s - 3ms/step - accuracy: 0.6417 - loss: 0.5507 - val_accuracy: 0.6573 - val_loss: 0.5395
Epoch 3/50
275/275 - 1s - 3ms/step - accuracy: 0.6545 - loss: 0.5367 - val_accuracy: 0.6614 - val_loss: 0.5328
Epoch 4/50
275/275 - 1s - 3ms/step - accuracy: 0.6551 - loss: 0.5336 - val_accuracy: 0.6573 - val_loss: 0.5275
Epoch 5/50
275/275 - 1s - 3ms/step - accuracy: 0.6603 - loss: 0.5297 - val_accuracy: 0.6582 - val_loss: 0.5306
Epoch 6/50
275/275 - 1s - 3ms/step - accuracy: 0.6577 - loss: 0.5268 - val_accuracy: 0.6559 - val_loss: 0.5251
Epoch 7/50
275/275 - 1s - 5ms/step - accuracy: 0.6595 - loss: 0.5274 - val_accuracy: 0.6559 - val_loss: 0.5245
Epoch 8/50
275/275 - 1s - 3ms/step - accuracy: 0.6654 - loss: 0.5234 - val_accuracy: 0.6568 - val_loss: 0.5259
Epoch 9/50
275/275 - 1s - 3ms/step - accuracy: 0.6678 - loss: 0.5232 - val_accuracy: 0.6618 - val_loss: 0.5235


In [331]:
def predict_on_single_row(single_row_data):
    input_df = pd.DataFrame([single_row_data])


    if 'ID' in input_df.columns:
        input_processed = input_df.drop('ID', axis=1)
    else:
        input_processed = input_df.copy()


    input_cat = input_processed.select_dtypes(include = ['object'])
    input_num = input_processed.select_dtypes(include= ['int64'])


    input_scale = scaler.transform(input_num)


    input_ohe = ohe.transform(input_cat).toarray()


    input_final = np.concatenate((input_scale, input_ohe), axis=1)


    predictions = model.predict(input_final)


    predicted_class = np.argmax(predictions, axis=1)[0]


    if predicted_class == 1:
        result = "The shipment is predicted to reach on time."
    else:
        result = "The shipment is predicted NOT to reach on time."

    return predicted_class, result

In [332]:
user_input_series = pd.Series({
    'ID': 0,
    'Warehouse_block': 'D',
    'Mode_of_Shipment': 'Flight',
    'Customer_care_calls': 4,
    'Customer_rating': 2,
    'Cost_of_the_Product': 177,
    'Prior_purchases': 3,
    'Product_importance': 'low',
    'Gender': 'F',
    'Discount_offered': 44,
    'Weight_in_gms': 1233
})

predicted_class, prediction_result = predict_on_single_row(user_input_series)

print(f"Predicted Class: {predicted_class}")
print(f"Prediction Result: {prediction_result}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
Predicted Class: 1
Prediction Result: The shipment is predicted to reach on time.
